"""add username to events table

Revision ID: fbbc12969328
Revises: d9b575ba8d40
Create Date: 2024-11-18 12:00:17.600787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbc12969328'
down_revision = 'd9b575ba8d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_events_username_users'), 'users', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_username_users'), type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
